sudo: false
language: ruby
env:
  global:
  - APP_SECRET_TOKEN=b2724973fd81c2f4ac0f92ac48eb3f0152c4a11824c122bcf783419a4c51d8b9bba81c8ba6a66c7de599677c7f486242cf819775c433908e77c739c5c8ae118d
  matrix:
  - DATABASE_ADAPTER=mysql2
  - DATABASE_ADAPTER=postgresql DATABASE_USERNAME=postgres
rvm:
- 2.2.2
- 2.3.0
cache: bundler
script: bundle exec rake
notifications:
  pushover:
    api_key:
      secure: gDI6EguxXGcyDf+y6NovKAlbz6gg+orxHSp+lcMTZh8NGCuGMw85dy84gVwjsfSceHb/CUgdgEoVlw/gJjb/UfzrlVxN25VXuXpk5JBJT62VFgsFLLlpBKIFFi+wlBAwQ2T0pANCh/1U6XzhRlxJvzgbyVwIG8mGoUBMPxOEoajjajyll5zX78sC+OpCWoU02/RaIFCDMbFNeVnEvmtXm5x1qPEiUdLFONSZVstgtx++RNYk0Lvfvv/r5N+tv4IsbIph+aHG3P85JcCqvvmP0SnuNnkQo3eFchPNKpT8JivlhM7lnlVeVHlN/ZnB+jA91Yz55dukxGHxEVDHl3kYRpeyfK2X+OSHiYVTR3s5W6fIfxNsYTohMGkOGR2o1eof1YoTcQJAkGncR0QMeHEs62zUgN7f9ctvrEzsTqmZalh3GNev/vC2eKa4yZRqM6X3v/97RAeZTAUfYUOCMGxbS0Q9MH6oj4byEfLu/5VBnKEzBU164SERzEOy7Pc3b9kxF8O+cFD56vFvPG3EFAZ8YQqBikelJepEGSEdoRV3fCQ9MnQtp1QJSCs9pnsnvhpuotuOFy2TtpU3JaptiVJJ+aeIYWMiykjNmT2KNYl0426c8wRlsZwE48CPAieiGVibSPRKhrr4NUYSnKW++va91F6ZU6BaGstuEOXlT6xZ8HQ=
    users:
      secure: qKbQ4ST+z8EAmsy4wM1t0PrvojEyAHwFfLT/RRnQRWrzO9G9PxG+GuSggMc0QS5EAgnyImpxoIAVf2htEtiUtaTvY3yt98kO38sgVZ3PSqpoeK7XMsagHbmny4hvBw8//IDPtDbY8TgwDiXwRFvgXV30TQ1+Oox9AMSzHu3rsmLGa9+LPsEwjr6+ERiVUFgU0DXWe63NBizWz/qgLTF7MwIkFYBLNi2RZhD9BLk2u66yxWBGatgRA1/0ONxHp3bbdCmFigaBopbHMm7OB1z0xa1DkiDZHqqIQ1gWqVu35P3+IVGPzNgrnGC23FHHaBNjZgwZ5f5b/7mUsX9vBLuFt2KQoGmkZ2UxJggFhVoTbaTBjGFL9f0E3LNIJKdCk3lUQX9FAfsMTB6G1cm73itEsbQ0pLt3QZNlAHh4XxgLT4F7GqHASWhrZABhzwW/8sN4qR7m+2dufQC0n7LQT/Mk5HHcoDHGt8Xtku+ALHXSLtATlKMBVYTyyyc08UCEEv78uOh2eCIi/LE747bCp2rsNg3Gx26legPilMi4zWULbmfkKcCaPFLTOF2RgVO1FtcUwBfLYdO6KDtm1c4x0J4RCzqpojOKN3NkLlgcg0q9PwBEjVb9aME1nFxxKFX4sFreSNvQCV/5k4Vj5rgrGb7SxqRFss00CEn8D65zCgy5r+Y=
